Testing Clustering on January 2013

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
%matplotlib inline

In [2]:
january2013=pd.read_csv("datasets/yellow_tripdata_2013-01.csv")

In [8]:
january2013 = january2013[['pickup_latitude','pickup_longitude']]
january2013 = january2013.loc[(january2013['pickup_longitude'] > -74.06) & (january2013['pickup_longitude'] < -73.77) & (january2013['pickup_latitude'] > 40.61) &  (january2013['pickup_latitude'] < 40.91)]
january2013 = january2013.reset_index()
january2013 = january2013.drop('index', 1)

In [10]:
print(january2013.shape)
january2013.head()

(14496582, 2)


pickup_latitude  pickup_longitude
0        40.757977        -73.978165
1        40.731781        -74.006680
2        40.737770        -74.004711
3        40.759945        -73.974600
4        40.748528        -73.976252

In [41]:
%%time
kmeans_10 = KMeans(n_clusters = 10, n_init=1)
kmeans_10.fit(january2013)
labels = kmeans_10.labels_

Wall time: 1min 14s


In [42]:
kmeans_10.cluster_centers_

array([[ 40.72163039, -74.00448128],
       [ 40.77288012, -73.95496298],
       [ 40.64681734, -73.78553448],
       [ 40.74811194, -73.99427959],
       [ 40.76885831, -73.87198959],
       [ 40.75729441, -73.97583323],
       [ 40.77689952, -73.98121875],
       [ 40.68575972, -73.98150047],
       [ 40.80117161, -73.95922683],
       [ 40.73064852, -73.98441259]])

In [43]:
# Import a convenience function to split the sets.
from sklearn.cross_validation import train_test_split

# Generate the training set.  Set random_state to be able to replicate results.
train = january2013.sample(frac=0.8, random_state=1)
# Select anything not in the training set and put it in the testing set.
test = january2013.loc[~january2013.index.isin(train.index)]
# Print the shapes of both sets.
print(train.shape)
print(test.shape)

(11597266, 2)
(2899316, 2)


In [51]:
%%time
train_kmeans_10 = KMeans(n_clusters = 10, n_init=1)
train_kmeans_10.fit_predict(train)

Wall time: 1min 19s


In [52]:
%%time
test_kmeans_10 = KMeans(n_clusters = 10, n_init=1)
test_kmeans_10.fit(test)

Wall time: 24.9 s


In [53]:
train_kmeans_10.cluster_centers_

array([[ 40.74898514, -73.99507487],
       [ 40.7770144 , -73.98113726],
       [ 40.64680327, -73.78551736],
       [ 40.76889612, -73.87197735],
       [ 40.75720786, -73.97597789],
       [ 40.77279268, -73.95503166],
       [ 40.7330719 , -73.98715756],
       [ 40.69645945, -73.97251904],
       [ 40.72096746, -74.00457106],
       [ 40.80107219, -73.95919585]])

In [54]:
test_kmeans_10.cluster_centers_

array([[ 40.78604333, -73.95626811],
       [ 40.75104393, -73.98682763],
       [ 40.71852207, -73.84420193],
       [ 40.77036738, -73.8742856 ],
       [ 40.73268628, -73.99403656],
       [ 40.64596943, -73.78498806],
       [ 40.77216503, -73.98201954],
       [ 40.76146543, -73.96586409],
       [ 40.7157065 , -74.00725043],
       [ 40.69666889, -73.9722439 ]])

In [70]:
from geopy.geocoders import Nominatim
geolocator = Nominatim()

location_array = []
for x,y in kmeans_10.cluster_centers_:
    loc = geolocator.reverse((str(x)+','+(str(y))))
    location_array.append(loc.address.split(', ')[2])
print(location_array)

['SoHo', 'Upper East Side', 'Queens County', 'Chelsea', 'North Beach', 'Madison Avenue', 'West 71st Street', 'Boerum Hill', 'Morningside Heights', 'East Village']


In [74]:
kmeans_10.predict(january2013).clus

array([5, 0, 3, ..., 0, 3, 6])